# Generated by Django 5.0.1 on 2024-01-06 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=2)),
                ('bat', models.CharField(max_length=1)),
                ('thw', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('ht', models.CharField(max_length=255)),
                ('wt', models.CharField(max_length=255)),
                ('birthPlace', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
